kind: pipeline
name: update runtime

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: pull and restart
  commands:
  - cd /app/commspt-bot/
  - proxychians4 -q git pull
  - docker restart commspt-bot

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: bot_token
    to: 
      from_secret: chat_id
    socks5: socks5://10.50.0.3:7891